### ISSUE TITLE
Feature Request: Create TempDir in common "ObsidianHTML"-subfolder of temp directory

### ISSUE THREAD

**Issue by Gewerd-Strauss** [obsidian-html/obsidian-html#692] opened 2023-05-18 08:35 UTC
Hello,

this is maybe less of an issue for common users, but has been something I would strongly advise to change. 

ObsidianHTML will create a tempfolder of structure `C:\Users\User\AppData\Local\Temp\tmp%randomString%`, e.g. `C:\Users\User\AppData\Local\Temp\tmp0cmpdxg7` to work from.

The simple solution is to set `copy_vault_to_tempdir: False`, but that is not recommendable from a data safety position. Particularly people like me, who decide to develop on this project on their own will however certainly run into executions which exit prematurely, get stopped in debugger and restarted, or any other conceivable way of not reaching the cleanup routines. 

Thus, you can often end up with several dozen vault snapshots in your temp directory when debugging, which is really bad if you have limited space on `C:\` - as I do.

The only solution is to regularly go through the temp directory, find all vault copies that were created this way and delete them. And there lies the issue: The folders created by obsidianHTML are too nondescript. I mean, they have a common pattern, but I also have five other programs who create similarly named folders in the same directory.

This issue is easily solvable by moving `C:\Users\User\AppData\Local\Temp\tmp%randomString%` to `C:\Users\User\AppData\Local\Temp\ObsidianHTML\tmp%randomString%`. This way, you would have all output in the temp directory, neatly sorted and isolated from other potentially confusing folders. And cleaning up after debugging would be a matter of deleting the entire folder, instead of inspecting every single `tmp%randomString%`-folder in `C:\Users\User\AppData\Local\Temp\`.

---

I hope I could explain the issue and proposed solution properly.

Thank you, once again, for this continually amazing tool. It is a legitimate life-saver, even if I seemingly manage to break it anew every day :P

Sincerely,  
~Gw

---

Anecdotally, shouldn't adding a folder to `exclude_subfolders`, e.g.

    exclude_subfolders:
      - "".git""
      - "".obsidian""
      - "".trash""
      - "".vscode""
      - "".DS_Store""
    
prevent those folders from being copied to the temp directory anyways? They shouldn't be processed anyways, so why spend the overhead for copying them? Especially disk-intense folders such as `.git` are annoying to deal with once they become large enough (as an example, my vault is at 5k commits, `.git` is worth 6 of the 14.5GB of total vault size).

**Comment by dwrolvink** [comment] 2023-05-18 11:44
exclude_subfolders should do that for the copy step, indeed, if it is still copying those files I will need to look into it.

the v4 syntax for including/excluding files is:
``` yaml
module_config: {}
  get_file_list:
    include_glob:
      value: '*'
    exclude_glob:
      value: 
        - ".obsidian/**/*"
        - ".trash/**/*",
        - ".DS_Store/**/*",
        - ".git/**/*",
```

Which should give a file list to then be copied over to the tempdir. Currently these are still separate systems. I will make sure that:

- The `get_file_list` module is executed first (and then all the other filtering modules) to arrive at a definite files.json list
- Use this files.json list to only copy those files to the tempdir
- Have the tempdir just be: `<Obsidian Appdir>/tempdir`
  - So on windows just `C:\Users\User\AppData\Local\Temp\ObsidianHTML\tempdir`
  - This folder is not cleaned up automatically upon exit, aiding in troubleshooting
  - This folder is removed at the start of every run, making sure that we don't get a proliferation of tempdirs

I think that is a very good course of action, and kind of an obvious solution of which I am not sure how I missed it. I think the copy vault feature preceeds the appdir code, so I never considered that option.

**Comment by Gewerd-Strauss** [comment] 2023-05-18 13:57
> exclude_subfolders should do that for the copy step, indeed, if it is still copying those files I will need to look into it.
> 
> the v4 syntax for including/excluding files is:
> 
> ```yaml
> module_config: {}
>   get_file_list:
>     include_glob:
>       value: '*'
>     exclude_glob:
>       value: 
>         - ".obsidian/**/*"
>         - ".trash/**/*",
>         - ".DS_Store/**/*",
>         - ".git/**/*",
> ```
> 
> Which should give a file list to then be copied over to the tempdir. Currently these are still separate systems. I will make sure that:

This will then still just to be added to the config file, and should then be valid on master/v4.0.0_beta only. Am I understanding you correctly that this is not yet implemented (your answer is a bit ambiguous with respect to tense there)?

If so, I will do a few tests once this was implemented for testing to see if this will alleviate the issue on my end, and come back once I have more definitive answers. If it is already implemented, please confirm and I will go forth and do my usual test suite.

---

> Steps you outlined

I think this is also a better solution than what I was proposing, because rarely you would have reason to keep the temp directory anyways when heading into the next execution - it would be cleaned anyways, so the only reason when it is _not_ cleaned is if the script exits prematurely/a debugger is closed prematurely etc.  
So it is probably safe to assume that the user does not care about the tempdir data in normal usecases, and only really has an interest in looking at them when errors occur - which the user gets to learn about when errors are thrown either in terminal or in-code. Only at that point would said user - both during normal usage or while developing and debugging - have any reason to take a closer look at the copied data - and thus it will be sufficient to use a static directory name that gets wiped and reused on each execution to prevent data buildup.

**Comment by dwrolvink** [comment] 2023-05-18 14:03
You have the config that I showed, and the `exclude_glob` by itself. Currently, copy_temp_vault uses the latter, and the filtering should be applied. The plan is to have it use the output of get_file_list, and then the exclude_glob (on its own) should be able to be deprecated.

I'd suggest waiting till the changes are made that I proposed, I'll test the exclusion then and then you can pull and confirm.

**Comment by Gewerd-Strauss** [comment] 2023-05-18 14:11
> I'd suggest waiting till the changes are made that I proposed, I'll test the exclusion then and then you can pull and confirm.

Alright, will do so. Thank you.

**Comment by dwrolvink** [comment] 2023-05-18 16:25
Initial `index/files.json`:

``` json
[
  "/home/dorus/git/example_vault/vault/Blog/200w.gif",
  "/home/dorus/git/example_vault/vault/Blog/Armadillo WITH some Caps.md",
  "/home/dorus/git/example_vault/vault/Blog/Cats.md",
  "/home/dorus/git/example_vault/vault/Blog/Welcome to my Homepage!.md",
  "/home/dorus/git/example_vault/vault/Blog/pictures - or something?.md",
  "/home/dorus/git/example_vault/vault/Blog/\u00dcber.md",
  "/home/dorus/git/example_vault/vault/Home.md",
  "/home/dorus/git/example_vault/vault/Links2/Markdown links absolute.md",
  "/home/dorus/git/example_vault/vault/Links2/Markdown links relative.md",
  "/home/dorus/git/example_vault/vault/Links2/Obsidian links.md",
  "/home/dorus/git/example_vault/vault/Site1/Site 1 Homepage.md",
  "/home/dorus/git/example_vault/vault/Site1/Site 1 Page.md",
  "/home/dorus/git/example_vault/vault/Site2/Site 2 page.md",
  "/home/dorus/git/example_vault/vault/Site2/Site2 Homepage.md",
  "/home/dorus/git/example_vault/vault/bla.jpg",
  "/home/dorus/git/example_vault/vault/cat.png",
  "/home/dorus/git/example_vault/vault/custom.css",
  "/home/dorus/git/example_vault/vault/formula.svg",
  "/home/dorus/git/example_vault/vault/img tags.md",
  "/home/dorus/git/example_vault/vault/inline_tags/note-1.md",
  "/home/dorus/git/example_vault/vault/inline_tags/note-2.md",
  "/home/dorus/git/example_vault/vault/subfolder/Home.md",
  "/home/dorus/git/example_vault/vault/subfolder/subsubfolder/subnote.md",
  "/home/dorus/git/example_vault/vault/test_default_config.md"
]
```
After applying this custom config:
``` yaml
module_config: 
  get_file_list:
    include_glob:
      value: '*'
    exclude_glob:
      value: 
        - ".obsidian/**/*"
        - ".trash/**/*"
        - ".DS_Store/**/*"
        - ".git/**/*"
        - "Links2/**/*"              # <-- addition relative to default config
```

We first get (after `get_files_list` is done running):
``` json
[
  "/home/dorus/git/example_vault/vault/Blog/200w.gif",
  "/home/dorus/git/example_vault/vault/Blog/Armadillo WITH some Caps.md",
  "/home/dorus/git/example_vault/vault/Blog/Cats.md",
  "/home/dorus/git/example_vault/vault/Blog/Welcome to my Homepage!.md",
  "/home/dorus/git/example_vault/vault/Blog/pictures - or something?.md",
  "/home/dorus/git/example_vault/vault/Blog/\u00dcber.md",
  "/home/dorus/git/example_vault/vault/Home.md",
  "/home/dorus/git/example_vault/vault/Site1/Site 1 Homepage.md",
  "/home/dorus/git/example_vault/vault/Site1/Site 1 Page.md",
  "/home/dorus/git/example_vault/vault/Site2/Site 2 page.md",
  "/home/dorus/git/example_vault/vault/Site2/Site2 Homepage.md",
  "/home/dorus/git/example_vault/vault/bla.jpg",
  "/home/dorus/git/example_vault/vault/cat.png",
  "/home/dorus/git/example_vault/vault/custom.css",
  "/home/dorus/git/example_vault/vault/formula.svg",
  "/home/dorus/git/example_vault/vault/img tags.md",
  "/home/dorus/git/example_vault/vault/inline_tags/note-1.md",
  "/home/dorus/git/example_vault/vault/inline_tags/note-2.md",
  "/home/dorus/git/example_vault/vault/subfolder/Home.md",
  "/home/dorus/git/example_vault/vault/subfolder/subsubfolder/subnote.md",
  "/home/dorus/git/example_vault/vault/test_default_config.md"
]
```

Notice that the `Links2` files are gone.

> These file versions are obtained by setting `keep_module_file_versions: True`. This will create the folder `versions` under the module_data_folder, containing all of the different versions of the modfiles, prefixed with timestamps, so that you can see which module does what to each file. This is useful in the case of `index/files.json`, as it gets created by `get_files_list`, and then sequentially updated by the next modules, such as `filter_on_metadata`, and finally `copy_vault_to_tempdirectory`.

Once `copy_vault_to_tempdirectory` has run, the `index/files.json` file will look like this, and this is currently the definitive content that is used by the core of obsidianhtml:

``` json
[
  "/home/dorus/.config/obsidianhtml/tmpdir/input/Blog/200w.gif",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/Blog/Armadillo WITH some Caps.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/Blog/Cats.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/Blog/Welcome to my Homepage!.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/Blog/pictures - or something?.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/Blog/\u00dcber.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/Home.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/Site1/Site 1 Homepage.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/Site1/Site 1 Page.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/Site2/Site 2 page.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/Site2/Site2 Homepage.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/bla.jpg",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/cat.png",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/custom.css",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/formula.svg",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/img tags.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/inline_tags/note-1.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/inline_tags/note-2.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/subfolder/Home.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/subfolder/subsubfolder/subnote.md",
  "/home/dorus/.config/obsidianhtml/tmpdir/input/test_default_config.md"
]
```

Notice the new folder location.

Currently, the code uses a very crude way to copy the files from the input_folder to their new home:
``` python
    def copy_file(self, src_path, dst_path):
        dst_path.parent.mkdir(parents=True, exist_ok=True)
        with open(src_path, "rb") as r:
            with open(dst_path, "wb") as w:
                w.write(r.read())
```

Main pro is that this cuts out all the code pertaining to shutil, shutil_walk, rsync, and the code to choose between them. This should also be way more cross-platform compatible, as the python `open()` should be very well supported.

Main con is that this is probably extremely slow as compared to `rsync` or similar methods. For the vaults in my possession, this still seems to be at max 2 seconds, so kind of insignificant compared to the time increase on large vaults happening in the conversion step, but something to keep an eye on anyways.

If the filtering behavior as shown here is not working on your system, this is probably because the windows file paths use `\` instead of `/`, and the globs use `/`. I'd expect the Paths library to "get" this though, and there have been other users on Windows that confirmed filtering worked for them in its current form. But let me know if you still get filtered folders in your appdir folder.

**Comment by Gewerd-Strauss** [comment] 2023-05-18 20:01
Took me a while because of Windows **DAMN FRIGGING GODAWFUL STUPID PIECE OF SHIT** `MAX_PATH=260` pathlength limitation oh my **FRIGGING** god\*. >:/ 

Finally relented and enabled long paths, let's see how much of the stuff I use breaks over the coming days...

The good news: it works™ so far. 
The better news for me: Took the opportunity to take some pruning on what I let be copied and now the copied over vault is "only" 5,08GB in size, instead of 14,5GB - so that will probably also speed things up quite a bit :P

---

Sidenote you may or may not be aware of:

> `C:\Users\Claudius Main\AppData\Local\obsidianhtml\obsidianhtml\tmpdir\input`

The generated `obsidianhtml`-folder is nested twice. While this may make no difference, as long a there is no reason for it this should be rectified. At least on windows this is important since the aforementioned **STUPID** 260 char limit can easily trip users who maybe don't even know that this can be circumvented, or who are not comfortable editing their registry to enable long paths.
Just don't see why we would "waste" 13 characters when there is an entire vault copied into that folder which may or may not already contain some pretty nested folders.

---


> 2 seconds

Is this the time for the entire execution chain, or copying-only? If it is for copy-only, how do I measure that? I can time full execution pretty consistently, if not with ms-accuracy, but that's not the precision  I'd be realistically interested in anyways.

---

<sup>*You might have noticed I have a certain hatred towards the path limitation. It has hurt me numerous times in the past, and I usually prefer not to touch the registry, but today broke the camel's back on this.</sup>

**Comment by dwrolvink** [comment] 2023-05-18 23:27
> The generated obsidianhtml-folder is nested twice.

This is correct, the format is `<publisher>/<app>`, in our case, `obsidianhtml/obsidianhtml`.

> Just don't see why we would "waste" 13 characters when there is an entire vault copied into that folder which may or may not already contain some pretty nested folders.

Good point. These are the standards set by microsoft though. And if I save 13 characters, there is no guarantee that another user won't have an extra nested folder in their vault and the problem would persist. 

There is a method of using long paths with python, which should work without the registry setting edit, though that is notorious for introducing new bugs, which is prepending all paths with: `\\?\`

This would be applied by using a function like this to add this to any absolute path:

``` python
def longname(path):
    normalized = os.fspath(path.resolve())
    if not normalized.startswith('\\\\?\\'):
        normalized = '\\\\?\\' + normalized
    return pathlib.Path(normalized)
```

Problem is that relative paths are tricky, and `\foo\..\bar` is not allowed, forward slashes are not allowed, etc. This is pretty tricky with the current code setup, and even worse because I have to setup my work laptop to test this on Windows, which is pretty tedious.

Might be worth it to take some time to dive into this sometime soon. 

> Is this the time for the entire execution chain, or copying-only? 

Its the time between this line appearing:
```
[ INFO  ] module.controller.run_module() :: copy_vault_to_tempdirectory.run()
```
And the next line appearing:
```
[ INFO  ] module.controller.run_module() :: prepare_output_folders.run()
```

You could time this by [measuring the execution](https://stackoverflow.com/questions/1557571/how-do-i-get-time-of-a-python-programs-execution) of : 
https://github.com/obsidian-html/obsidian-html/blob/6e3c575b278eea196a68dd89ea55b06c35740ae6/obsidianhtml/modules/builtin/copy_vault_to_tempdirectory.py#L52-L100

**Comment by dwrolvink** [comment] 2023-05-19 11:31
I wonder, do you have experience with running Docker containers on your system?

A solution might be for me to publish a docker image that binds an input and output folder, and when you run it, it converts the input folder into the output folder. All the operations within the docker container **should** be posix based, and might circumvent the path limit issue. 

If you are familiar with docker this might be a valid solution to the "it works on my computer but not yours" issues we are facing.

**Comment by dwrolvink** [comment] 2023-05-19 14:23
See: https://github.com/obsidian-html/obsidian-html/blob/master/examples/docker/readme.md

**Comment by Gewerd-Strauss** [comment] 2023-05-20 06:46
I am just noting that I won't be able to look into this for the close forseeable future but will try and do so once I encounter the issue again. Debugging without an issue is both pointless and hard, and I have a really full plate right now anyways - so as long ass it is not broken I have much more pressing matters to spend my time on currently.

**Comment by dwrolvink** [comment] 2023-05-20 10:17
Fair enough! The title of the issue is fixed, so I'm closing this then. Just know that the docker method exists, as does the [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install), both of which might solve all the windows specific issues that you might face now/in the future.

**Closed as completed by dwrolvink** 2023-05-20 10:17 UTC
Labels: enhancement, Waiting for feedback, fixed in master
