### ISSUE TITLE
Do not crash on empty `tags:` frontmatter

### ISSUE THREAD

**Issue by aquatix** [obsidian-html/obsidian-html#348] opened 2022-08-31 11:24 UTC
I have/had several notes with an empty `tags:` entry in the frontmatter, because I hadn't thought of a tag to add there yet.

obsidianhtml then just plain crashes on trying to iterate over a None value, without telling which file is being processed.

I'd like to either have it being able to copy with those empty values, or crash (which is fine with me), but tell me which file has the empty tag 'set'.

Thanks for this nice tool, I discovered it today, but I'm getting more enthousiastic by the minute :)

The crash happens with both the official release and the latest version from git.

**Comment by dwrolvink** [comment] 2022-08-31 11:26
Should be very doable, especially for the tags key.
And happy that you are enjoying the package!

**Comment by dwrolvink** [comment] 2022-08-31 11:31
A quick workaround would be to instead of having this in your notes/templates:
``` yaml
---
tags: 
---
``` 

To have this:
``` yaml
---
tags: []
---
``` 

This will make the type an empty list,  instead of a NoneType, and should work as intended.

It has been a recurring issue though that it is hard to tell which note is causing the issue. You can add `-v` to the command to run in verbose mode, which should make it possible to tell which note is causing the issue, but I think it is time to pass through a state object to every function telling us which note is being processed at the moment, so that it can be shared on every (planned) raised error.

**Comment by aquatix** [comment] 2022-08-31 11:49
I could add the brackets to my 'new note' template indeed, but it indeed feels like a work-around specifically for obsidian-html (and in another vault I don't use a template).

Ah, `-v` sounds helpful, that at least gives context about which file is being processed.

Yeah, passing state around is a problem I've been struggling with too in my projects :)

Anyway, thanks for your time and effort!

**Comment by dwrolvink** [comment] 2022-08-31 11:57
As related to the other issue, I will also just cast NoneTypes to lists so that you don't have to edit all your files.
Will revamp this issue to "passing state" and add what I just wrote to the other issue as they are related.

**Comment by aquatix** [comment] 2022-08-31 11:59
Awesome, sounds like that would work great. Thanks!

**Comment by dwrolvink** [comment] 2022-08-31 12:35
As said, fixed in #349 and just created #351 to work on adding error information. (Decided to close this issue anyways)

**Closed as completed by dwrolvink** 2022-08-31 12:35 UTC
Labels: enhancement
