### ISSUE TITLE
Horizontal rulers not displayed correctly

### ISSUE THREAD

**Issue by DominikDoom** [obsidian-html/obsidian-html#446] opened 2022-10-26 17:35 UTC
Standalone horizontal rulers aren't rendered as a line but as a box.
I believe this is due to obsidian-html thinking they are used as part of a header notation, meaning
```md
Title
---
```
becomes

Title
---

However, even when the dashes are not used as part of a header, the anchor link element is still added to the hr element (with a broken anchor). Since the svg used for the anchor symbol is contained inside, this causes it to have height instead of just being a line.

A simple test is just
```md
# Test

---

Lorem ipsum...
```
which will render the line as intended in obsidian but result in this:
![image](https://user-images.githubusercontent.com/34448969/198095108-2d5e1c79-5f6b-4fbb-8190-a6fe43d6a9b8.png)
with a broken `index.html#!` anchor link href.

**Comment by dwrolvink** [comment] 2022-10-27 06:45
Thank you for the bug report.
This should now be fixed in master.

It was caused by some very old code, so it has been broken for a long time now.
What happened was that the code that makes the **h**1, **h**2, etc tags into anchor links, also hit the **h**r, because I had the dumb code of 

``` js
        if (typeof els[i].tagName === 'undefined' || els[i].tagName[0] != 'H') {
            continue;
        }
```

Changed it into 
``` js
        if (typeof els[i].tagName === 'undefined' || els[i].tagName[0] != 'H' || els[i].tagName == 'HR' ) {
            continue;
        }
```

And that fixes it for me.

This leaves only `<header>, <html>, <head>` as other tags that can be matched in error. But this is unlikely, because only objects in the container div are matched, so this should be all there is to this issue.

**Closed as completed by dwrolvink** 2022-10-27 06:45 UTC
Labels: bug
